### ISSUE TITLE
Compatibility with 2021.8

### ISSUE THREAD

**Issue by northalpha** [kellerza/hassio-sma-em#6]
Would it be possible to modify the addon to work with the statistics changes made in 2021.8 that we can use the Energy Dashboard? That would be awesome, so we would be able to get rid off the awful sunnyportal stuff.

**Comment by kellerza** [comment]
Have not checked if this is supported by MQTT autodiscovery yet, if that is the case it should be possible

**Comment by johnnysmithy852456** [comment]
Hi
Looks like it could just be the device Class power (pcomsume)  HA is only adding entities with a Energy class at the moment.

**Comment by kellerza** [comment]
From addon version 2021.8.1 (released 5 min ago) you can change the MQTT autodiscover config that gets sent to homeassistant:

```
AUTODISCOVER_CONFIG:
  - key: state_class
    value: measurement
  - key: last_reset
    value: '2021-07-30T00:00:00+00:00'
```

state_class is the new default when you update

It seems that last_reset is NOT supported by MQTT auto-discovery today, so you can try to use customize to override the entities with that,- refer to [this](https://community.home-assistant.io/t/long-term-statistics-from-mqtt/326990) solution
